DIMPOLIBIO EQU 6
INTERR EQU 57H

DATOS SEGMENT
  ALFABETO DB '456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123'
  LUT DB 255 DUP(0, 0)
  STR1 DB 'POLIBIO$'
  STR2 DB '44 43 36 33 22 33 43$'
  TRESESPACIOS DB '   ', '$'
DATOS ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
PILA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO EXTRA
EXTRA SEGMENT
RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
EXTRA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
INICIO PROC
; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
MOV AX, DATOS
MOV DS, AX
MOV AX, PILA
MOV SS, AX
MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
; FIN DE LAS INICIALIZACIONES
; COMIENZO DEL PROGRAMA

CALL ROSETTA

MOV BX, 1 ; HACEMOS QUE INT 57H IMPRIMA DEL TIRON
MOV AX, SEG STR1
MOV DS, AX
MOV DX, OFFSET STR1
MOV AH, 10H
INT INTERR

MOV AX, SEG STR2
MOV DS, AX
MOV DX, OFFSET STR2
MOV AH, 11
INT INTERR

; FIN DEL PROGRAMA
MOV AX, 4C00H
INT 21H
INICIO ENDP

; IMPRIME LA LUT PARA PASAR EL CÓDIGO A POLIBIO
ROSETTA PROC
  PUSH AX BX DX DI SI

  ; DEJAR LA PRIMERA CASILLA VACÍA
  MOV AH, 9
  MOV DX, OFFSET TRESESPACIOS
  INT 21H

  ; SELECCIONAR EL MODO DE IMPRESIÓN CARACTER A CARACTER
  MOV AH, 2

  MOV DI, 0

  ; IMPRIMIR FILA CABECERA CON LAS COORDENADAS DE LAS COLUMNAS
  COORDENADAS_COLUMNAS:
    ; IMPRIMIR UN ESPACIO ANTES DE LA COORDENADA
    MOV DL, ' '
    INT 21H

    ; IMPRIMIR COORDENADA
    MOV DX, DI
    ADD DL, '1' ; TODO: COMENTAR QUE EL LADRILLITO DE SERGIO NO SE ENTERA Y PUEDE QUE QUECO TAMPOCO
    INT 21H

    ; IMPRIMIR OTRO ESPACIO DESPUÉS DE LA COORDENADA
    MOV DL, ' '
    INT 21H

    INC DI
    CMP DI, DIMPOLIBIO
    JNZ COORDENADAS_COLUMNAS


  ; IMPRIMIR UN SALTO DE LINEA
  MOV DL, 0AH
  INT 21H

  ; INICIALIZAR COORDENADAS DE LA TABLA
  MOV BX, 0 ; OFFSET DE LA FILA EN LA TABLA
  MOV SI, 0 ; FILA

  IMPRIMIR_FILA:
    MOV DI, 0 ; COLUMNA

    ;; PRIMERA COLUMNA
    MOV DL, ' '
    INT 21H

    ; IMPRIMIR EL ÍNDICE DE LA FILA
    MOV DX, SI
    ADD DL, '1'
    INT 21H

    MOV DL, ' '
    INT 21H

    IMPRIMIR_CASILLA:
      MOV DL, ' '
      INT 21H

      MOV DL, ALFABETO[BX][DI]
      INT 21H

      MOV DL, ' '
      INT 21H

      INC DI
      CMP DI, DIMPOLIBIO
      JNZ IMPRIMIR_CASILLA


    ; IMPRIMIR UN SALTO DE LINEA
    MOV DL, 0AH
    INT 21H

    ADD BX, DIMPOLIBIO
    INC SI

    CMP SI, DIMPOLIBIO
    JNZ IMPRIMIR_FILA

    MOV DL, 0AH
    INT 21H


  POP SI DI DX BX AX
  RET
ENDP ROSETTA

; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO
